/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppNav {}
  interface AppNavAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface ManageQuestions {}
  interface ManageQuestionsAttributes extends StencilHTMLAttributes {}

  interface StartQuiz {}
  interface StartQuizAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppNav': Components.AppNav;
    'AppRoot': Components.AppRoot;
    'ManageQuestions': Components.ManageQuestions;
    'StartQuiz': Components.StartQuiz;
  }

  interface StencilIntrinsicElements {
    'app-nav': Components.AppNavAttributes;
    'app-root': Components.AppRootAttributes;
    'manage-questions': Components.ManageQuestionsAttributes;
    'start-quiz': Components.StartQuizAttributes;
  }


  interface HTMLAppNavElement extends Components.AppNav, HTMLStencilElement {}
  var HTMLAppNavElement: {
    prototype: HTMLAppNavElement;
    new (): HTMLAppNavElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLManageQuestionsElement extends Components.ManageQuestions, HTMLStencilElement {}
  var HTMLManageQuestionsElement: {
    prototype: HTMLManageQuestionsElement;
    new (): HTMLManageQuestionsElement;
  };

  interface HTMLStartQuizElement extends Components.StartQuiz, HTMLStencilElement {}
  var HTMLStartQuizElement: {
    prototype: HTMLStartQuizElement;
    new (): HTMLStartQuizElement;
  };

  interface HTMLElementTagNameMap {
    'app-nav': HTMLAppNavElement
    'app-root': HTMLAppRootElement
    'manage-questions': HTMLManageQuestionsElement
    'start-quiz': HTMLStartQuizElement
  }

  interface ElementTagNameMap {
    'app-nav': HTMLAppNavElement;
    'app-root': HTMLAppRootElement;
    'manage-questions': HTMLManageQuestionsElement;
    'start-quiz': HTMLStartQuizElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
