/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface NavComponent {}
  interface NavComponentAttributes extends StencilHTMLAttributes {}

  interface QuestionsComponent {}
  interface QuestionsComponentAttributes extends StencilHTMLAttributes {}

  interface QuizComponent {}
  interface QuizComponentAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'NavComponent': Components.NavComponent;
    'QuestionsComponent': Components.QuestionsComponent;
    'QuizComponent': Components.QuizComponent;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'nav-component': Components.NavComponentAttributes;
    'questions-component': Components.QuestionsComponentAttributes;
    'quiz-component': Components.QuizComponentAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLNavComponentElement extends Components.NavComponent, HTMLStencilElement {}
  var HTMLNavComponentElement: {
    prototype: HTMLNavComponentElement;
    new (): HTMLNavComponentElement;
  };

  interface HTMLQuestionsComponentElement extends Components.QuestionsComponent, HTMLStencilElement {}
  var HTMLQuestionsComponentElement: {
    prototype: HTMLQuestionsComponentElement;
    new (): HTMLQuestionsComponentElement;
  };

  interface HTMLQuizComponentElement extends Components.QuizComponent, HTMLStencilElement {}
  var HTMLQuizComponentElement: {
    prototype: HTMLQuizComponentElement;
    new (): HTMLQuizComponentElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'nav-component': HTMLNavComponentElement
    'questions-component': HTMLQuestionsComponentElement
    'quiz-component': HTMLQuizComponentElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'nav-component': HTMLNavComponentElement;
    'questions-component': HTMLQuestionsComponentElement;
    'quiz-component': HTMLQuizComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
